export type Question = {
  cat: string;
  word: string;
  options: string[];
  answer: string;
  tip: string;
};

export const Q: Question[] = [
  { cat: "S ou Z", word: "CA__A", options: ["S", "Z"], answer: "S", tip: "Casa se escreve com S." },
  { cat: "S ou Z", word: "A__UL", options: ["S", "Z"], answer: "Z", tip: "Azul se escreve com Z." },
  { cat: "G ou J", word: "__IRASSOL", options: ["G", "J"], answer: "G", tip: "Girassol tem som de GI, com G." },
  { cat: "G ou J", word: "HO__E", options: ["G", "J"], answer: "J", tip: "Hoje se escreve com J." },
  { cat: "X ou CH", word: "__UVA", options: ["X", "CH"], answer: "CH", tip: "Chuva se escreve com CH." },
  { cat: "X ou CH", word: "PEI__E", options: ["X", "CH"], answer: "X", tip: "Peixe se escreve com X." },
  { cat: "R ou RR", word: "CA__O", options: ["R", "RR"], answer: "RR", tip: "Carro tem som forte entre vogais, por isso RR." },
  { cat: "R ou RR", word: "CA__INHO", options: ["R", "RR"], answer: "R", tip: "Carinho tem som fraco, por isso R." },
  { cat: "M ou N", word: "CA__PO", options: ["M", "N"], answer: "M", tip: "Antes de P e B usamos M: campo." },
  { cat: "M ou N", word: "CA__TO", options: ["M", "N"], answer: "N", tip: "Canto se escreve com N." },
  { cat: "C ou SS", word: "PA__ARO", options: ["C", "SS"], answer: "SS", tip: "Passaro se escreve com SS: passaro/passaro no jogo sem acento." },
  { cat: "C ou CEDILHA", word: "CORA__AO", options: ["C", "\u00c7"], answer: "\u00c7", tip: "Coracao leva cedilha antes de A, O ou U." },
  { cat: "L ou U", word: "FINA__", options: ["L", "U"], answer: "L", tip: "Final termina com L." },
  { cat: "L ou U", word: "CE__", options: ["L", "U"], answer: "U", tip: "Ceu termina com U." },
  { cat: "E ou I", word: "M__NINO", options: ["E", "I"], answer: "E", tip: "Menino se escreve com E na primeira silaba." },
  { cat: "E ou I", word: "P__PINO", options: ["E", "I"], answer: "E", tip: "Pepino se escreve com E." },
  { cat: "O ou U", word: "B__NITO", options: ["O", "U"], answer: "O", tip: "Bonito se escreve com O." },
  { cat: "O ou U", word: "C__RUJA", options: ["O", "U"], answer: "O", tip: "Coruja se escreve com O." },
  { cat: "H inicial", word: "__OMEM", options: ["H", "O"], answer: "H", tip: "Homem tem H inicial." },
  { cat: "H inicial", word: "__ORTA", options: ["H", "O"], answer: "H", tip: "Horta tem H inicial." },
  { cat: "QU ou C", word: "__ENTE", options: ["QU", "C"], answer: "QU", tip: "Quente se escreve com QU." },
  { cat: "QU ou C", word: "__ASA", options: ["QU", "C"], answer: "C", tip: "Casa se escreve com C no inicio." },
  { cat: "GU ou G", word: "__ITARRA", options: ["GU", "G"], answer: "GU", tip: "Guitarra se escreve com GU." },
  { cat: "GU ou G", word: "__ATO", options: ["GU", "G"], answer: "G", tip: "Gato se escreve com G." },

  { cat: "S ou SS", word: "A__ADO", options: ["S", "SS"], answer: "SS", tip: "Assado tem SS entre vogais." },
  { cat: "S ou SS", word: "PA__ADO", options: ["S", "SS"], answer: "SS", tip: "Passado tem SS entre vogais." },
  { cat: "S ou SS", word: "PE__OA", options: ["S", "SS"], answer: "SS", tip: "Pessoa se escreve com SS." },
  { cat: "S ou SS", word: "MI__AO", options: ["S", "SS"], answer: "SS", tip: "Missao tem SS." },
  { cat: "S ou SS", word: "PROFI__AO", options: ["S", "SS"], answer: "SS", tip: "Profissao se escreve com SS." },
  { cat: "S ou SS", word: "PRE__AO", options: ["S", "SS"], answer: "SS", tip: "Pressao tem SS." },
  { cat: "S ou SS", word: "A__UNTO", options: ["S", "SS"], answer: "SS", tip: "Assunto se escreve com SS." },
  { cat: "S ou SS", word: "A__ISTIR", options: ["S", "SS"], answer: "SS", tip: "Assistir se escreve com SS." },
  { cat: "S ou SS", word: "PA__EIO", options: ["S", "SS"], answer: "SS", tip: "Passeio se escreve com SS." },
  { cat: "S ou SS", word: "SUCE__O", options: ["S", "SS"], answer: "SS", tip: "Sucesso tem SS." },
  { cat: "S ou SS", word: "GRO__O", options: ["S", "SS"], answer: "SS", tip: "Grosso se escreve com SS." },
  { cat: "S ou SS", word: "TRAVE__EIRO", options: ["S", "SS"], answer: "SS", tip: "Travesseiro tem SS no meio." },
  { cat: "S ou SS", word: "IMPRE__ORA", options: ["S", "SS"], answer: "SS", tip: "Impressora se escreve com SS." },
  { cat: "S ou SS", word: "E__ENCIAL", options: ["S", "SS"], answer: "SS", tip: "Essencial comeca com ESSE, por isso SS." },
  { cat: "S ou SS", word: "DI__E", options: ["S", "SS"], answer: "SS", tip: "Disse se escreve com SS." },

  { cat: "R ou RR", word: "TE__ENO", options: ["R", "RR"], answer: "RR", tip: "Terreno tem som forte de R entre vogais: RR." },
  { cat: "R ou RR", word: "FE__O", options: ["R", "RR"], answer: "RR", tip: "Ferro tem RR." },
  { cat: "R ou RR", word: "BA__IGA", options: ["R", "RR"], answer: "RR", tip: "Barriga tem RR." },
  { cat: "R ou RR", word: "CO__IDA", options: ["R", "RR"], answer: "RR", tip: "Corrida tem som forte de R: RR." },
  { cat: "R ou RR", word: "GUE__A", options: ["R", "RR"], answer: "RR", tip: "Guerra se escreve com RR." },
  { cat: "R ou RR", word: "SO__ISO", options: ["R", "RR"], answer: "RR", tip: "Sorriso se escreve com RR." },
  { cat: "R ou RR", word: "HO__OR", options: ["R", "RR"], answer: "RR", tip: "Horror tem RR no meio." },
  { cat: "R ou RR", word: "TO__ADA", options: ["R", "RR"], answer: "RR", tip: "Torrada se escreve com RR." },
  { cat: "R ou RR", word: "MA__OM", options: ["R", "RR"], answer: "RR", tip: "Marrom tem RR." },
  { cat: "R ou RR", word: "VA__ER", options: ["R", "RR"], answer: "RR", tip: "Varrer tem RR." },
  { cat: "R ou RR", word: "CA__EGA", options: ["R", "RR"], answer: "RR", tip: "Carrega tem RR." },
  { cat: "R ou RR", word: "BEZE__O", options: ["R", "RR"], answer: "RR", tip: "Bezerro se escreve com RR." },
  { cat: "R ou RR", word: "CA__ETA", options: ["R", "RR"], answer: "RR", tip: "Carreta tem RR." },
  { cat: "R ou RR", word: "BA__ULHO", options: ["R", "RR"], answer: "R", tip: "Barulho tem apenas um R." },
  { cat: "R ou RR", word: "GA__OTO", options: ["R", "RR"], answer: "R", tip: "Garoto tem R fraco entre vogais: um R." },

  { cat: "X ou CH", word: "MO__ILA", options: ["X", "CH"], answer: "CH", tip: "Mochila se escreve com CH." },
  { cat: "X ou CH", word: "BI__O", options: ["X", "CH"], answer: "CH", tip: "Bicho se escreve com CH." },
  { cat: "X ou CH", word: "MA__ADO", options: ["X", "CH"], answer: "CH", tip: "Machado se escreve com CH." },
  { cat: "X ou CH", word: "CO__ILO", options: ["X", "CH"], answer: "CH", tip: "Cochilo se escreve com CH." },
  { cat: "X ou CH", word: "FA__ADA", options: ["X", "CH"], answer: "CH", tip: "Fachada se escreve com CH." },
  { cat: "X ou CH", word: "BO__ECHA", options: ["X", "CH"], answer: "CH", tip: "Bochecha tem CH." },
  { cat: "X ou CH", word: "EN__ENTE", options: ["X", "CH"], answer: "CH", tip: "Enchente se escreve com CH." },
  { cat: "X ou CH", word: "RE__EIO", options: ["X", "CH"], answer: "CH", tip: "Recheio se escreve com CH." },
  { cat: "X ou CH", word: "CA__ORRO", options: ["X", "CH"], answer: "CH", tip: "Cachorro tem CH no inicio do som." },
  { cat: "X ou CH", word: "A__AR", options: ["X", "CH"], answer: "CH", tip: "Achar se escreve com CH." },
  { cat: "X ou CH", word: "LI__A", options: ["X", "CH"], answer: "X", tip: "Lixa se escreve com X." },
  { cat: "X ou CH", word: "ME__ER", options: ["X", "CH"], answer: "X", tip: "Mexer se escreve com X." },
  { cat: "X ou CH", word: "__ICARA", options: ["X", "CH"], answer: "X", tip: "Xicara se escreve com X." },
  { cat: "X ou CH", word: "__ADREZ", options: ["X", "CH"], answer: "X", tip: "Xadrez se escreve com X." },
  { cat: "X ou CH", word: "EN__AME", options: ["X", "CH"], answer: "X", tip: "Enxame se escreve com X." },
  { cat: "X ou CH", word: "__ERIFE", options: ["X", "CH"], answer: "X", tip: "Xerife se escreve com X." },
  { cat: "X ou CH", word: "BRU__A", options: ["X", "CH"], answer: "X", tip: "Bruxa se escreve com X." },
  { cat: "X ou CH", word: "ABACA__I", options: ["X", "CH"], answer: "X", tip: "Abacaxi se escreve com X." }
];
